# Generated by Django 3.2.4 on 2023-03-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20230322_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_section',
            name='mail',
            field=models.CharField(default=' tbiexecutivedirector@nehrucolleges.com', max_length=200),
            preserve_default=False,
        ),
    ]
