# Generated by Django 3.2.4 on 2023-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_contact_section_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacteditpage',
            old_name='Address',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='contacteditpage',
            old_name='mail',
            new_name='Address2',
        ),
        migrations.AddField(
            model_name='contacteditpage',
            name='mail1',
            field=models.CharField(default='Dr. A.P.J. Abdul Kalam Block, Nehru Group of Institutions, Thirumalayampalayam, Coimbatore – 641 105,Tamil Nadu.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacteditpage',
            name='mail2',
            field=models.CharField(default='tbiexecutivedirector@nehrucolleges.com', max_length=200),
            preserve_default=False,
        ),
    ]
